config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  get 'search' => 'searchs#seach'
  
  # フォロー機能
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  resources :users do
    get :follow, on: :member
    get :follower, on: :member
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, length: { in: 1..200 }
  belongs_to :user

  # フォロー機能
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # いいね機能
  has_many :favorites, dependent: :destroy

  # 検索機能
    def self.looks(searches, words)
      if searches == "perfect_match"
        @book = Book.where("title LIKE?","#{words}")
      elsif searches == "forward_match"
        @book = Book.where("title LIKE?","#{words}%")
      elsif searches == "backward_match"
        @book = Book.where("title LIKE?","%#{words}")
      elsif searches == "partial_match"
        @book = Book.where("title LIKE?","%#{words}%")
      else
        @book = Book.all
      end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness:true, length: {in: 2..20}
  validates :introduction,length: { maximum: 50}


  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy

  # フォロー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
    # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # いいね機能
  has_many :favorites, dependent: :destroy

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  # 検索機能
  def self.looks(searches, word)
    if searches == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  
  def after_sign_in_path_for(resource)
    user_path(resource) # ログイン後に遷移するpathを設定
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :editing_user, only: [:edit]

  def new
    @book = Book.new
  end

  def create
    @booknew = Book.new(book_params) 
    @booknew.user_id =  current_user.id 
    @user = current_user
  if @booknew.save 
    redirect_to book_path(@booknew.id), notice: 'Book was successfully created'  
  else
    @books = Book.all
    render :index
  end
end

  def index
    @books = Book.all
    @booknew = Book.new
    @user = current_user
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated!'
    else
      
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def editing_user
    book = Book.find(params[:id])
    if book.user != current_user 
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    # redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def follow
    current_user.follow(params[:id])
    redirect_back(fallback_location: root_path)
  end
  
  def unfollow
    current_user.unfollow(params[:id])
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def seach
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word]) #ユーザーから探す処理(user.rbのlooksメソッドを使用)
    else
      @books = Book.looks(params[:search], params[:word]) #投稿から探す処理(book.rbのlooksメソッドを使用)
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  
  def follow
    @user = User.find(params[:id])
    @users = @user.follower
  end
  
  def follower
    @user = User.find(params[:id])
    @users = @user.followed
  end

  def index
    @user = current_user
    @users = User.all
    @booknew = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @booknew = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
  else
    redirect_to user_path(current_user)
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice: 'Book was successfully updated!'
    else
      render :edit
  end
end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
    <p id="notice"></p>
    <% if model.errors.any? %>
  <div id="error_explanation">
    <h3 class="text-danger"><%= pluralize(model.errors.count,"error") %> prohibited this product from being saved:</h3>

  <ul><% model.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
</div>
    <% end %>

app/views/books/_form.html.erb
    <h2 class="mt-3">New book</h2>
      <%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit btn, class:"btn btn-success col-xs-12" %>
  </div>
  <% end %>

app/views/books/_index.html.erb
    <table class="table table-hover table-invers">
      <thead>
        <th></th>
          <th>title</th>
            <th>opinion</th>
              <th colspan="3"></th>
                <% @books.each do |book| %>
                <tr><td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: "50x50",fallback: "no_image.jpg"%>
                    <% end %></td>
                    <td><%= link_to book.title, book_path(book.id) %></td>
                    <td><%= book.body %></td>
                    <td id="favorite_buttons_<%= book.id %>">
                      <%= render 'favorites/favorite', book: book %>
                    </td>
                </tr>
              <% end %>
            </table>
          </div>
        </tr>
      </thead>
    </tbody>
  </table>

app/views/books/edit.html.erb
<div class='container'>
  <%= render 'books/error', model: @book %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
    <table>
          <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit btn: "Update Book", class:"btn btn-success col-xs-12" %>
        </div>
            <% end %>
        <td class="show"><%= link_to "Show", book_path(@book.id) %></td>
        <td>|</td>
        <td class="back"><%= link_to "Back", books_path %></td>
    </table>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div class='container px-5 px-sm-0'>
<%= render 'books/error', model: @booknew %>
    <div class='row'>
        <div class='col-md-3'>
            <table class='table'>
                <%= render 'users/profile', user: @user %>
            </table>
                
            <div>
                <%= render 'books/form', {book: @booknew, btn: 'Create Book'} %>
            </div>
        </div>
            <div class='col-md-8 offset-md-1'>
                <h2>Books</h2>
                <%= render 'books/index', book: @books %>
                
            </div>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <table class='table'>
          <%= render 'users/profile', user: @user %>
      </table>

        <div>
          <tr><%= render 'books/form', {book:@booknew, btn: 'Create Book'} %></tr>
        </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <table class="table table-user-show">
        <tr>
        <h2>Book detail</h2>
        <tbody>
        </tr>
        <td><%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg"%><br>
            <% end %>
            <%= link_to @user.name, user_path(@user) %>
        </td>
        <td><%= link_to @book.title %></td>
        <td><%= @book.body %></td>
        <td id="favorite_buttons_<%= @book.id %>">
          <%= render 'favorites/favorite', book: @book %></td>
        <% if @book.user_id == current_user.id %>
        <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", book_path, method: :delete, class:"btn btn-sm btn-danger", "data-confirm"=> "Are you sure?" %></td>
            <% end %>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
                <% if current_user.already_favorited?(book) %>
                  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                  <%= book.favorites.count %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post, remote: true  do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                  <%= book.favorites.count %>
                <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class='container'>
    <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
    </div>
</main>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
    <p id="notice"></p>
    <% if user.errors.any? %>
<div id="error_explanation">
    <h3 class="text-danger"><%= pluralize(user.errors.count,"error") %> prohibited this product from being saved:</h3>
<ul><% user.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
    </ul>
</div>
<% end %>
<% end %>

app/views/layouts/_form.html.erb
<div class="text-center">
<% if user_signed_in? %>
      <%= form_with url: search_path, method: :get, local: :true do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"], ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索" %>
      <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Bookers2</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

<body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><a class="fas fa-home nav-link text-light" href="<%= user_path(current_user.id) %>"> home</a></li>
          <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
          <li><%= link_to "logout", destroy_user_session_path, class:"fas fa-sign-out-alt nav-link text-light",method: :delete %></li>
        <% else %>
          <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
          <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
          <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
          <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
    <% if flash[:alert] %>
    <div class="text-success">
      <p class="alert"><%= alert %></p>
    </div>
      <% end %>
      <% if flash[:notice] %>
    <div class="text-success">
      <p class="notice"><%= notice %></p>
    </div>
      <% end %>
</header>

    <%= render 'layouts/form' %>
  <%= yield %>
    <footer class="footer">
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/searchs/seach.html.erb
<p id="notice"></p>
<div class="mx-auto" style="width: 1200px;">
  <% if @range == "User" %>
    <h2>Users search</h2>
      <%= render 'users/index', user: @users %> <%# 検索対象がUserのとき、ユーザーを一覧表示 %>
  <% else %>
    <h2>Book search</h2>
    <%= render 'books/index', book: @books %> <%# 検索対象がBookのとき、投稿を一覧表示 %>
<% end %>
</div>

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, size: "40x40",fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table table-user">
  <h2>User info</h2>
		<tr><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></tr>
		<tr>
		  <th>name</th>
		  <th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th><%= "follow" %></th>
			<th><%= link_to "#{user.follower.count}", follow_user_path(user.id) %></th>
		</tr>
		<tr>
			<th><%= "follower" %></th>
			<th><%= link_to "#{user.followed.count}", follower_user_path(user.id) %></th>
		</tr>
		<tr>
			<% unless current_user == user %>
        <% if current_user.following?(user) %>
          <th><%= link_to 'Unfollow', unfollow_path(user.id), method: :POST, class: 'btn btn-outline-danger' %></th>
        <% else %>
          <th><%= link_to 'Follow', follow_path(user.id), method: :POST, class: 'btn btn-outline-primary' %></th>
        <% end %>
      <% end %>
		</tr>
</table>

	<div class="row">
  	<td><%= link_to " ", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %></td>
	</div>
<%# 編集ボタンについて %>
<%# <% if user.id == current_user.id %> 
<%# <% else %>
<%# <td><%= link_to " ", user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
<%# <% end %>

app/views/users/edit.html.erb
  <div class="container">
          <p id="notice"></p>
        <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3 class="text-danger"><%= pluralize(@user.errors.count,"error") %> prohibited this product from being saved:</h3>
        <ul><% @user.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
        <% end %>
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
          <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
              <label>name</label>
              <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
                <label>Image</label>
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"form-control-file user_image" %>
          </div>
          <div class="form-group">
              <label>introduction</label>
              <%= f.text_area :introduction, class:"form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>

app/views/users/follow.html.erb
<p id="notice"></p>
<div class='col-md-10 offset-md-1'>
  <h3>Follow Users</h3>
    <% if @users.empty? %>
        <span>ユーザーはいません</span>
    <% else %>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th colspan="4"></th>
        </tr>
      </thead>
        <tbody>
            <% @user.following_user.where.not(id: current_user.id).each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg" , size:"40x40" %></td>
            <td><%= "#{user.name}" %></td>
            <td><%="フォロー数:#{user.follower.count}" %></td>
            <td><%= "フォロワー数:#{user.followed.count}" %></td>
            <td><%= link_to "show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/follower.html.erb
<p id="notice"></p>
<div class='col-md'>
  <h3>Follower Users</h3>
    <% if @users.empty? %>
        <span>ユーザーはいません</span>
    <% else %>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th colspan="4"></th>
        </tr>
      </thead>
        <tbody>
          <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
            <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg" , size:"40x40" %></td>
              <td><%= "#{user.name}" %></td>
              <td><%="フォロー数:#{user.follower.count}" %></td>
              <td><%= "フォロワー数:#{user.followed.count}" %></td>
              <td><%= link_to "show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/index.html.erb
  <p id="notice"></p>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <table class="table">
        <tr><%= render 'users/profile', user: @user %></tr>
        </table>
        <div>
          <%= render 'books/form', {book: @booknew, btn: 'Create Book'} %>
        </div>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size: "40x40",fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= "フォロー数:#{user.follower.count}" %></td>
          <td><%= "フォロワー数:#{user.followed.count}" %></td>
          <td>
            <% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
              <% else %>
                <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
              <% end %>
          </td>
          <% end %>
            <td><%= link_to "Show", "/users/#{user.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <table class='table'>
        <tr><%= render 'users/profile', user: @user %></tr>
      </table>

      <div>
        <tr><%= render 'books/form', {book: @booknew, btn: 'Create Book'} %></tr>
      </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
          </thead>
            <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40",fallback: "no_image.jpg"%>
            <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </table>
        </tr>
      </table>
    </div>
  </div>
</div>